In [2]:
pip install torch

   ---------------------------------------- 0.0/198.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/198.6 MB 6.5 MB/s eta 0:00:31
   ---------------------------------------- 0.6/198.6 MB 7.4 MB/s eta 0:00:27
   ---------------------------------------- 1.0/198.6 MB 7.7 MB/s eta 0:00:26
   ---------------------------------------- 1.4/198.6 MB 7.3 MB/s eta 0:00:28
   ---------------------------------------- 1.7/198.6 MB 7.1 MB/s eta 0:00:28
   ---------------------------------------- 2.0/198.6 MB 7.2 MB/s eta 0:00:28
   ---------------------------------------- 2.5/198.6 MB 7.5 MB/s eta 0:00:27
    --------------------------------------- 2.8/198.6 MB 7.6 MB/s eta 0:00:26
    --------------------------------------- 3.2/198.6 MB 7.6 MB/s eta 0:00:26
    --------------------------------------- 3.6/198.6 MB 7.6 MB/s eta 0:00:26
    --------------------------------------- 4.0/198.6 MB 7.8 MB/s eta 0:00:26
    --------------------------------------- 4.3/198.6 MB 7.7 MB/s eta 0


[notice] A new release of pip is available: 23.3.2 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [5]:
import torch
x = torch.Tensor([5,3])
y = torch.Tensor([2,1])

print(x*y)

tensor([10.,  3.])


In [6]:
x= torch.zeros([2,5])

In [7]:
print(x)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [8]:
x.shape

torch.Size([2, 5])

In [9]:
y=torch.rand([2,5])
print(y)

tensor([[0.7623, 0.4352, 0.3643, 0.4117, 0.7780],
        [0.4954, 0.0750, 0.1832, 0.6082, 0.2267]])


In [10]:
y.view([1,10])

tensor([[0.7623, 0.4352, 0.3643, 0.4117, 0.7780, 0.4954, 0.0750, 0.1832, 0.6082,
         0.2267]])

In [11]:
y

tensor([[0.7623, 0.4352, 0.3643, 0.4117, 0.7780],
        [0.4954, 0.0750, 0.1832, 0.6082, 0.2267]])

In [12]:
y=y.view([1,10])

In [13]:
y

tensor([[0.7623, 0.4352, 0.3643, 0.4117, 0.7780, 0.4954, 0.0750, 0.1832, 0.6082,
         0.2267]])